name: Integration Tests

on:
  push:
    branches:
      - "main"
      - "beta"
      - "develop"

env:
  CI_TOOLS_VERSION: "3.2.0-beta.2"

jobs:
  run-integration-tests:
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    name: Run integration tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.300

      - name: Add nuget source
        run: dotnet nuget add source "${{ secrets.NUGET_PUSH_SOURCE }}" -n "github" -u "${{ secrets.PACKAGES_USER }}" -p "${{ secrets.PACKAGES_TOKEN }}" --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore ./TodoistRestApiClient.sln

      - name: Build sources
        run: dotnet build -c Release --no-restore

      - name: Test sources (Integration Tests)
        timeout-minutes: 5
        run: dotnet test -c Release --no-restore --no-build
        working-directory: ./tests/TodoistRestApiClient.IntegrationTests
        env:
          TodoistRestApiClient__ApiToken: ${{ secrets.TODOIST_REST_API_TOKEN }}
